# Generated by Django 2.2.3 on 2019-09-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_auto_20190913_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(null=True, upload_to='post_pics'),
        ),
    ]
