# Generated by Django 2.2.3 on 2019-09-13 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_auto_20190913_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='slug',
        ),
    ]
