# Generated by Django 2.2.3 on 2019-09-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
