# Generated by Django 2.2.3 on 2019-09-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_activity_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='target',
            field=models.TextField(max_length=150),
        ),
    ]
