# Generated by Django 2.2.3 on 2019-09-17 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20190915_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='author',
            new_name='activity_author',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='description',
            new_name='activity_description',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='name',
            new_name='activity_name',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='target',
            new_name='activity_target',
        ),
    ]
