# Generated by Django 2.2.3 on 2019-09-17 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20190917_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='activity_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='activity_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='activity_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='activity_target',
            new_name='target',
        ),
    ]
