# Generated by Django 2.2.3 on 2019-10-02 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_activity_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('A', 'Arts'), ('A', 'Adventure'), ('B', 'Business'), ('D', 'Design'), ('E', 'Entertainment'), ('ED', 'Education'), ('H', 'Health'), ('FT', 'Fitness'), ('FA', 'Fashion'), ('FD', 'Food'), ('M', 'Music'), ('P', 'Programming'), ('S', 'Startup'), ('T', 'Technology'), ('O', 'Other')], default=None, max_length=100, null=True),
        ),
    ]
