# Generated by Django 2.2.3 on 2019-10-05 21:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_auto_20191002_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
