# Generated by Django 2.2.3 on 2019-10-07 20:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_activity_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
