# Generated by Django 2.2.3 on 2019-10-17 22:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0011_auto_20191017_1002'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookmarkActivity',
            new_name='Bookmark',
        ),
    ]
