# Generated by Django 2.2.3 on 2019-10-22 00:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0012_auto_20191017_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='bookmark',
            field=models.ManyToManyField(blank=True, related_name='bookmark', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('A', 'Arts'), ('A', 'Adventure'), ('B', 'Business'), ('D', 'Design'), ('Entertainment', 'Entertainment'), ('ED', 'Education'), ('H', 'Health'), ('FT', 'Fitness'), ('FA', 'Fashion'), ('FD', 'Food'), ('M', 'Music'), ('P', 'Programming'), ('S', 'Startup'), ('T', 'Technology'), ('O', 'Other')], default=None, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
