# Generated by Django 2.2.3 on 2019-11-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0014_remove_activity_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.ImageField(null=True, upload_to='activity_pics'),
        ),
    ]
