# Generated by Django 2.2.3 on 2019-11-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0015_activity_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('Arts', 'Arts'), ('Adventure', 'Adventure'), ('Business', 'Business'), ('Design', 'Design'), ('Entertainment', 'Entertainment'), ('Education', 'Education'), ('Health', 'Health'), ('Fitness', 'Fitness'), ('Fashion', 'Fashion'), ('Food', 'Food'), ('Music', 'Music'), ('Programming', 'Programming'), ('Startup', 'Startup'), ('Technology', 'Technology'), ('Other', 'Other')], default=None, max_length=100, null=True),
        ),
    ]
